### PR TITLE
new internet web-site

### PR DESCRIPTION
**Pull request by ciolt**
Hi guys I set out to give the site a facelift, while also allowing it to scale with a new seamless Gulp/Pug-based build system. I also added some nifty SEO stuff in the head, and yes the Google Analytics tags are still there and working.

image

Here's a screenshot of the blog page

image

Of course, it's also responsive.

image

I also fixed some stuff like minor typos and minimized some stuff like a GIF that was over 1MB in size (usually slows down page load and Google doesn't like that)

### CODE REVIEW

**Comment by ifedapoolarewaju** [comment]
oh dear!! 😍 

cc @bankks

**Comment by bankks** [comment]
Whoah! I'll take a better look later but looks nice! Good job guys! 🤩
Sorry I didn't give any update yet, it's because I just got hired to an amazing job and I'm moving to São Paulo city and also it was Brazil's carnival last week haha so I've been really busy with all these stuff, but it's on my personal milestone for the next week! 💪 
Let's do this!

**Comment by ciolt** [comment]
Any status on the pull request?

**Comment by ifedapoolarewaju** [comment]
@ciolt yes this looks good to me. Merging now

**Pull request merged**
