### PR TITLE
Shaswa123 darkmode

### PR DESCRIPTION
**Pull request by shaswa123**

### CODE REVIEW

**Comment by shaswa123** [comment]
Was able to add dark mode to the app.

**Comment by shaswa123** [comment]
Hello,
Did you find this useful?

**Comment by Imparium** [comment]
Apparently the owner of igdm is having little to no time to continue the project.

**Comment by shaswa123** [comment]
Oh, that's pretty sad. Well, that's alright if you ask me. Thanks for telling me that.

**Comment by ifedapoolarewaju** [comment]
Thank you for sending the PR! My thought on this is that I think it's going to be tough to maintain 2 versions of css (dark and light mode). I think we could maybe try to use a single css file but use css variables to switch between light and dark mode. Does this make sense to you?

PS: sorry for taking too long to review 🙏

**Comment by shaswa123** [comment]
Yes, it does make sense. I can surely do what you are asking! I will close this and thank you.

**Pull request closed without merging**
