### PR TITLE
fix not able to contact new people

### LINKED ISSUE #1062: cant send new message to a new person

### PR DESCRIPTION
**Pull request by someone857**
fixes #1062

### CODE REVIEW

**Comment by someone857** [comment]
Also fixes #1075, #1073, #1071, #1060, #1058 and #1055 
:) looks like people don't read opened issues before logging a new one...

**Comment by someone857** [comment]
@ifedapoolarewaju if you can take a look, this is a bit massive right now...

**Comment by ifedapoolarewaju** [comment]
thank you!

**Comment by someone857** [comment]
> fixes #1062, #1075, #1073, #1071, #1060, #1058 and #1055

looks like we should have pre-fixed each issue with "fixes", otherwise it doesn't close automatically.. can you close them?

also, how often do you create a new release? I think a 2.7.1 could be useful right now with this fix

**Pull request merged**
